# Generated by Django 3.0 on 2022-02-09 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignatedParcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=400)),
                ('delivery_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('delivery_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designated', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Parcel')),
            ],
        ),
    ]
