# Generated by Django 3.0 on 2021-12-16 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_parcel_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignatedParcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=400)),
                ('is_active', models.BooleanField(default=True)),
                ('delivery_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='designated', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Parcel')),
            ],
        ),
    ]
