# Generated by Django 3.0 on 2021-12-23 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='designatedparcel',
            name='delivery_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
