# Generated by Django 3.0 on 2021-12-23 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+2341234567890'. Up to 20 digits allowed.", regex='^\\+?1?\\d{9,20}$')], verbose_name='phone'),
        ),
    ]
