# Generated by Django 3.0 on 2021-12-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20211223_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('delivery_admin', 'Delivery Admin'), ('admin', 'Admin'), ('delivery_user', 'Delivery User')], default='user', max_length=300),
        ),
    ]
