# Generated by Django 3.0 on 2022-01-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20211224_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_key',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
