# Generated by Django 3.0 on 2022-01-14 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220114_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='logistic_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='account.LogisticPartner'),
        ),
    ]
