# Generated by Django 3.0 on 2021-12-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
