# Generated by Django 3.0 on 2021-11-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxlocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boxlocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
