# Generated by Django 3.0 on 2021-12-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_parcel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='dropoff_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parcel',
            name='pickup_used',
            field=models.BooleanField(default=False),
        ),
    ]
