# Generated by Django 3.0 on 2021-11-25 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20211117_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxlocation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='boxlocation',
            name='longitude',
        ),
        migrations.AddField(
            model_name='selfstorage',
            name='drop_off',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='selfstorage',
            name='pick_up',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_for', models.CharField(max_length=300)),
                ('reference', models.CharField(max_length=300)),
                ('currency', models.CharField(max_length=300)),
                ('transaction_date', models.CharField(max_length=400)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
