# Generated by Django 3.0 on 2021-12-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211215_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
