# Generated by Django 3.0 on 2021-12-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_parcel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='delivery_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
