# Generated by Django 3.0 on 2021-12-23 00:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_parcel_delivery_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='delivery_code',
        ),
        migrations.AlterField(
            model_name='parcel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+2341234567890'. Up to 20 digits allowed.", regex='^\\+?1?\\d{9,20}$')]),
        ),
    ]
