# Generated by Django 3.0 on 2021-12-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211223_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('dropped', 'Dropped'), ('completed', 'Completed')], default='pending', max_length=300),
        ),
    ]
