# Generated by Django 3.0 on 2021-12-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211224_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
