# Generated by Django 3.0 on 2022-01-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_parcel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxlocation',
            name='center_apikey',
            field=models.CharField(blank=True, max_length=2000, null=True, unique=True),
        ),
    ]
