# Generated by Django 3.0 on 2022-01-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_boxlocation_center_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='compartment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
