# Generated by Django 3.0 on 2022-01-13 17:33

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_parcel_compartment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxlocation',
            name='center_apikey',
            field=models.CharField(blank=True, default=main.models.create_box_key, max_length=255, null=True, unique=True),
        ),
    ]
