# Generated by Django 3.0 on 2022-01-14 12:52

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20220114_1352'),
        ('main', '0011_auto_20220113_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, default=main.models.get_partner, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.LogisticPartner'),
        ),
    ]
