# Generated by Django 3.0 on 2022-01-17 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20220114_1352'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_auto_20220117_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, default=main.models.get_partner, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.LogisticPartner'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='main.BoxLocation'),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
