# Generated by Django 3.0 on 2022-01-26 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0014_auto_20220117_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_code', models.CharField(max_length=255)),
                ('bin', models.CharField(max_length=250)),
                ('last4', models.CharField(max_length=255)),
                ('exp_month', models.CharField(max_length=255)),
                ('exp_year', models.CharField(max_length=255)),
                ('card_type', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('account_name', models.CharField(max_length=600)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
