# Generated by Django 3.0 on 2022-01-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_carddetail_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddetail',
            name='account_name',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
