# Generated by Django 3.0 on 2022-02-04 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20220204_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxsize',
            old_name='size',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='compartment',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compartments', to='main.Category'),
        ),
        migrations.AlterField(
            model_name='compartment',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='compartment',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compartments', to='main.BoxSize'),
        ),
    ]
