# Generated by Django 3.0 on 2022-02-04 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20220204_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxlocation',
            name='available_space',
        ),
        migrations.AddField(
            model_name='boxlocation',
            name='available_large_space',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boxlocation',
            name='available_medium_space',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boxlocation',
            name='available_small_space',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boxlocation',
            name='available_xlarge_space',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='boxlocation',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.BoxSize'),
        ),
        migrations.AlterField(
            model_name='boxsize',
            name='name',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Xlarge')], max_length=255, unique=True),
        ),
    ]
