# Generated by Django 3.0 on 2022-02-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220204_2001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxlocation',
            name='size',
        ),
    ]
