# Generated by Django 3.0 on 2022-02-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_parcel_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='size',
        ),
        migrations.AlterField(
            model_name='parcel',
            name='compartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Compartment'),
        ),
    ]
