# Generated by Django 3.0 on 2022-02-07 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20220114_1352'),
        ('main', '0024_auto_20220205_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxlocation',
            name='available_xxlarge_space',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boxsize',
            name='name',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('xlarge', 'Xlarge'), ('xxlarge', 'XXlarge')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.LogisticPartner'),
        ),
    ]
